baseURL = "https://devs.miami"
title = "Devs.Miami"
author = "Robert Melrose"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
# hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
googleAnalytics = "G-TVBXEK65L2"

# Disqus Comment System
# disqusShortname = ""

[params]

  mainSections = ['blog']

  googleFonts = true

  [params.logo]
    main = "img/logo/logo.svg"
    alt = "Devs Miami Logo"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.site]
    name = "Devs.Miami"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "Miami Based Software Engineers"
    meta_og_title = "Devs.Miami"
    meta_og_type = "website"
    meta_og_url = "https://devs.miami"
    meta_og_image = "https://raw.githubusercontent.com/melroser/devs.miami/master/images/tn.png"
    meta_og_description = "A small network of software engineers and tech enthusiasts living in and around Miami."
    meta_twitter_card = "summary_large_image"
    meta_twitter_site = "@elonmusk"
    meta_twitter_creator = "@elonmusk"

[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 1

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 4

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Github"
    url = "https://github.com/melroser/devs.miami"
    pre = "<i class='icon-github text-2xl'></i>"
      weight = 2

